packaging_format = 2

id = "phpback"
name = "PHPBack"
description.en = "Feedback system you can use for your website"
description.fr = "Système de commentaires que vous pouvez utiliser pour votre site Web"

version = "1.3.2~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0-only"
website = "https://www.phpback.org/"
demo = "https://www.phpback.org/demo/"
code = "https://github.com/phpback/phpback"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/feedback"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/phpback/phpback/archive/refs/tags/v1.3.2.tar.gz"
        sha256 = "51dff0437ab754c7dd58d689ed0caf930ff8ab554d7c335df28efa2ec933e74f"


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.2-mysql"

    [resources.database]
    type = "mysql"
